### PR TITLE
Fix overlay for unmet dependencies

### LINKED ISSUE #158: Fix modal depth for conflicting popup
screenshot from 2018-04-17 16-45-16

### PR DESCRIPTION
**Pull request by nlowe**
Hack-y as hell but it works

Fixes #158

### CODE REVIEW

File: src/Athena/Controllers/ScheduleController.cs [hunk 1]
```diff
@@ -5,9 +5,6 @@ namespace Athena.Controllers
     [Route("[controller]")]
     public class ScheduleController : AthenaControllerBase
     {
-        [HttpGet]
-        public IActionResult ScheduleEditor() => View();
-
```
Comment (nchurchill) [inline src/Athena/Controllers/ScheduleController.cs]: thanks for removing this
